# Generated by Django 6.1 on 2026-08-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_referral_appointment_at_referral_completed_at_and_more'),
        ('inpatient', '0003_fluidbalance_icumonitoringsheet_icuthreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Optional inpatient admission this reading belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True),
        ),
    ]
