import { useState } from "react";
import { Plus, CalendarDays } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, getErrorMessage } from "@/lib/api";
import type { NurseShift, Paginated, Staff } from "@/lib/types";
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { useToast } from "@/hooks/use-toast";

export function ShiftManagementPage() { const client=useQueryClient(); const {data=[],isLoading}=useQuery({queryKey:["shifts"],queryFn:()=>api.get<Paginated<NurseShift>>("/shifts/",{params:{page_size:100}}).then(r=>r.data.results)}); return <div className="space-y-6"><PageHeader title="Shift management" description="Assign nurses, monitor coverage, and prevent scheduling conflicts."><CreateShift onDone={()=>client.invalidateQueries({queryKey:["shifts"]})}/></PageHeader><div className="grid gap-4 sm:grid-cols-3"><Stat label="Today's shifts" value={data.filter(x=>x.shift_date===new Date().toISOString().slice(0,10)).length}/><Stat label="On duty" value={data.filter(x=>x.effective_status==="active").length}/><Stat label="Upcoming" value={data.filter(x=>x.shift_date>=new Date().toISOString().slice(0,10)&&x.status!=="cancelled").length}/></div><div className="rounded-lg border"><div className="border-b p-4 font-medium">Scheduled shifts</div>{isLoading?<p className="p-5 text-sm text-muted-foreground">Loading…</p>:data.map(s=><div key={s.id} className="flex flex-wrap justify-between gap-2 border-b p-4 text-sm"><div><p className="font-medium">{s.nurse_details.first_name} {s.nurse_details.last_name} <span className="font-normal text-muted-foreground">· {s.department_name||"Unassigned"}</span></p><p className="text-muted-foreground">{s.shift_date} · {s.start_time.slice(0,5)}–{s.end_time.slice(0,5)} · {s.location||"No ward"}</p></div><span className="capitalize">{s.effective_status}</span></div>)}</div></div> }
const Stat=({label,value}:{label:string,value:number})=><div className="rounded-lg border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div>;
function CreateShift({onDone}:{onDone:()=>void}){const {success,error}=useToast();const [open,setOpen]=useState(false),[nurse,setNurse]=useState(""),[day,setDay]=useState(new Date().toISOString().slice(0,10)),[start,setStart]=useState("08:00"),[end,setEnd]=useState("16:00"),[type,setType]=useState("morning"),[location,setLocation]=useState("");const {data:staff}=useQuery({queryKey:["staff","nurses"],queryFn:()=>api.get<Paginated<Staff>>("/staff/",{params:{page_size:200}}).then(r=>r.data)});const m=useMutation({mutationFn:()=>api.post("/shifts/",{nurse:Number(nurse),shift_date:day,start_time:start,end_time:end,shift_type:type,location}),onSuccess:()=>{success("Shift assigned");setOpen(false);onDone()},onError:e=>error(getErrorMessage(e,"Unable to create shift."))});return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/> Create shift</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Assign nurse shift</DialogTitle></DialogHeader><div className="grid gap-4"><div><Label>Nurse</Label><Select value={nurse} onValueChange={setNurse}><SelectTrigger><SelectValue placeholder="Select nurse"/></SelectTrigger><SelectContent>{(staff?.results??[]).filter(s=>s.user_details.role_code==="nurse").map(s=><SelectItem key={s.id} value={String(s.user)}>{s.user_details.first_name} {s.user_details.last_name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-3 gap-2"><div><Label>Date</Label><Input type="date" value={day} onChange={e=>setDay(e.target.value)}/></div><div><Label>Start</Label><Input type="time" value={start} onChange={e=>setStart(e.target.value)}/></div><div><Label>End</Label><Input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div><Label>Shift type</Label><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["morning","afternoon","night","custom"].map(x=><SelectItem key={x} value={x} className="capitalize">{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Ward / location</Label><Input value={location} onChange={e=>setLocation(e.target.value)} /></div></div><DialogFooter><Button disabled={!nurse||m.isPending} onClick={()=>m.mutate()}><CalendarDays/>Assign shift</Button></DialogFooter></DialogContent></Dialog>}
