# Generated by Django 6.1 on 2026-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_relevance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('low_stock', 'Low Stock'), ('payment', 'Payment'), ('admission', 'Admission'), ('discharge', 'Discharge'), ('balance', 'Balance'), ('bed_assignment', 'Bed Assignment'), ('transfer', 'Patient Transfer'), ('handover', 'Shift Handover'), ('icu_alert', 'ICU Alert'), ('vitals', 'Vital Signs'), ('shift_reminder', 'Shift Reminder'), ('general', 'General')], default='general', max_length=32),
        ),
    ]
