# Generated by Django 6.1 on 2026-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_radiologist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Hospital Administrator'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('icu_nurse', 'ICU Nurse'), ('lab_technician', 'Laboratory Technician'), ('radiologist', 'Radiologist / Radiology Technician'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant / Cashier'), ('hr', 'HR / Staff Manager'), ('patient', 'Patient')], max_length=32, unique=True),
        ),
    ]
