# Generated by Django 6.1 on 2026-08-09 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_of_arrival', models.CharField(choices=[('ambulance', 'Ambulance'), ('walk_in', 'Walk-in'), ('referred', 'Referred'), ('police', 'Police'), ('other', 'Other')], default='walk_in', max_length=16)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('chief_complaint', models.TextField(blank=True)),
                ('triage_notes', models.TextField(blank=True)),
                ('triage_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vitals_summary', models.JSONField(blank=True, help_text='Snapshot of admission vitals.', null=True)),
                ('status', models.CharField(choices=[('triage', 'In Triage'), ('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('admitted', 'Admitted'), ('referred', 'Referred'), ('discharged', 'Discharged')], default='triage', max_length=16)),
                ('treatment_notes', models.TextField(blank=True)),
                ('referral_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_visits', to='patients.patient')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'arrival_time'],
                'indexes': [models.Index(fields=['status', 'priority'], name='emergency_e_status_5fc55e_idx')],
            },
        ),
    ]
