# Generated by Django 5.0.7 on 2026-08-12 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingnote',
            name='condition',
            field=models.CharField(choices=[('stable', 'Stable'), ('improving', 'Improving'), ('deteriorating', 'Deteriorating'), ('critical', 'Critical')], default='stable', max_length=16),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='interventions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='medication_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='patient_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='pending_tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('out_of_service', 'Out of Service')], default='available', max_length=16),
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='inpatient.admission')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='inpatient.bed')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ICUMonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('2_hourly', '2-hourly'), ('4_hourly', '4-hourly'), ('custom', 'Custom')], default='hourly', max_length=16)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=24)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consciousness', models.CharField(blank=True, max_length=120)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fluid_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('fluid_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('urine_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_support', models.TextField(blank=True)),
                ('infusions', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icu_records', to='inpatient.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=32)),
                ('condition', models.CharField(choices=[('stable', 'Stable'), ('improving', 'Improving'), ('deteriorating', 'Deteriorating'), ('critical', 'Critical')], default='stable', max_length=16)),
                ('observations', models.TextField(blank=True)),
                ('medication_due', models.TextField(blank=True)),
                ('pending_investigations', models.TextField(blank=True)),
                ('pending_tasks', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='inpatient.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
