# Generated by Django 6.1 on 2026-08-14 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_admission_numbers(apps, schema_editor):
    Admission = apps.get_model('inpatient', 'Admission')
    existing = set(
        Admission.objects.exclude(admission_number='')
        .values_list('admission_number', flat=True)
    )
    counter = 1
    for admission in Admission.objects.filter(admission_number='').order_by('id'):
        while True:
            candidate = f'ADM-BACKFILL-{counter:05d}'
            counter += 1
            if candidate not in existing:
                break
        existing.add(candidate)
        admission.admission_number = candidate
        admission.save(update_fields=['admission_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_nursingnote_condition_nursingnote_interventions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('balance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon / Evening'), ('night', 'Night')], default='morning', max_length=16)),
                ('oral_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('iv_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('urine_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('drain_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('other_output_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-balance_date', 'period'],
            },
        ),
        migrations.CreateModel(
            name='ICUMonitoringSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon / Evening'), ('night', 'Night')], default='morning', max_length=16)),
                ('interval', models.CharField(choices=[('15_minutes', 'Every 15 minutes'), ('30_minutes', 'Every 30 minutes'), ('hourly', 'Hourly'), ('2_hourly', '2-hourly'), ('4_hourly', '4-hourly')], default='hourly', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-monitoring_date', 'period'],
            },
        ),
        migrations.CreateModel(
            name='ICUThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parameter', models.CharField(choices=[('heart_rate', 'Heart rate (bpm)'), ('temperature', 'Temperature (°C)'), ('bp_systolic', 'Systolic BP (mmHg)'), ('bp_diastolic', 'Diastolic BP (mmHg)'), ('map', 'Mean arterial pressure (mmHg)'), ('respiratory_rate', 'Respiratory rate (bpm)'), ('spo2', 'SpO2 (%)'), ('blood_glucose', 'Blood glucose (mmol/L)'), ('gcs_total', 'GCS total'), ('pain_score', 'Pain score')], max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('min_alert', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_alert', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('min_critical', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_critical', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NurseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Nurse'), ('relief', 'Relief Nurse'), ('assist', 'Assisting Nurse')], default='primary', max_length=16)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingNoteAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_fields', models.JSONField(default=dict)),
                ('previous_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-amended_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='icumonitoringrecord',
            options={'ordering': ['recorded_at']},
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.RunPython(backfill_admission_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, help_text='Primary nurse responsible for this admission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_nursing_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='expected_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='notes',
            field=models.TextField(blank=True, help_text='Bed-specific notes (equipment, accessibility, etc.).'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='expected_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.room'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.ward'),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='blood_pressure_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='blood_pressure_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='drain_output_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='gcs_eye',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='gcs_motor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='gcs_verbal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='iv_intake_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='map_arterial',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mean arterial pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='oral_intake_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='other_output_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='oxygen_flow_rate',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='L/min', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='oxygen_therapy',
            field=models.CharField(blank=True, choices=[('room_air', 'Room air'), ('nasal_cannula', 'Nasal cannula'), ('face_mask', 'Face mask'), ('rebreather_mask', 'Non-rebreather mask'), ('venturi', 'Venturi mask'), ('mechanical_ventilation', 'Mechanical ventilation')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='positioning',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='pressure_injury_risk',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='pupil_left',
            field=models.CharField(blank=True, choices=[('reactive', 'Reactive'), ('sluggish', 'Sluggish'), ('fixed', 'Fixed'), ('dilated', 'Dilated'), ('equal_reactive', 'Equal & reactive')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='pupil_right',
            field=models.CharField(blank=True, choices=[('reactive', 'Reactive'), ('sluggish', 'Sluggish'), ('fixed', 'Fixed'), ('dilated', 'Dilated'), ('equal_reactive', 'Equal & reactive')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='skin_condition',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='spo2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='ventilator_mode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='ventilator_settings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.bed'),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='current_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='follow_up_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='handover_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='important_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='incoming_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='interventions_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='recent_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon / Evening'), ('night', 'Night')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='nursinghandover',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.ward'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='inpatient.nursingnote'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.bed'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('alert', 'Alert'), ('confused', 'Confused'), ('drowsy', 'Drowsy'), ('responsive_to_voice', 'Responsive to voice'), ('responsive_to_pain', 'Responsive to pain'), ('unresponsive', 'Unresponsive')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='doctor_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='fall_risk',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='fluid_intake_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='fluid_output_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_current_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_follow_up_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_important_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_interventions_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_pending_tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='handover_recent_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='mobility',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='nutrition_intake',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='pain_assessment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='patient_complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='safety_concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon / Evening'), ('night', 'Night')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('amended', 'Amended')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inpatient.ward'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='wound_dressing_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bedassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icumonitoringrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g. 120/80', max_length=24),
        ),
        migrations.AlterField(
            model_name='icumonitoringrecord',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('alert', 'Alert'), ('confused', 'Confused'), ('drowsy', 'Drowsy'), ('responsive_to_voice', 'Responsive to voice'), ('responsive_to_pain', 'Responsive to pain'), ('unresponsive', 'Unresponsive')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='icumonitoringrecord',
            name='frequency',
            field=models.CharField(choices=[('15_minutes', 'Every 15 minutes'), ('30_minutes', 'Every 30 minutes'), ('hourly', 'Hourly'), ('2_hourly', '2-hourly'), ('4_hourly', '4-hourly')], default='hourly', max_length=16),
        ),
        migrations.AlterField(
            model_name='icumonitoringrecord',
            name='respiratory_support',
            field=models.CharField(blank=True, choices=[('spontaneous', 'Spontaneous'), ('oxygen_therapy', 'Oxygen therapy'), ('bipap', 'BiPAP'), ('cpap', 'CPAP'), ('mechanical_ventilation', 'Mechanical ventilation')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='nursinghandover',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='shift',
            field=models.CharField(blank=True, help_text='Free-text shift label for legacy notes.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='bedassignment',
            index=models.Index(fields=['admission', '-assigned_at'], name='inpatient_b_admissi_c32a84_idx'),
        ),
        migrations.AddIndex(
            model_name='bedassignment',
            index=models.Index(fields=['bed', '-assigned_at'], name='inpatient_b_bed_id_5f063c_idx'),
        ),
        migrations.AddIndex(
            model_name='nursinghandover',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_n_admissi_a983d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingnote',
            index=models.Index(fields=['admission', '-recorded_at'], name='inpatient_n_admissi_abe7e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('admission',), name='uniq_active_admission_bed_assignment'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('bed',), name='uniq_active_bed_assignment'),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balances', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fluidbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icu_sheets', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_sheets', to='inpatient.bed'),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_sheets_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_sheets_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icumonitoringsheet',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icumonitoringrecord',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inpatient.icumonitoringsheet'),
        ),
        migrations.AddIndex(
            model_name='icumonitoringrecord',
            index=models.Index(fields=['admission', 'recorded_at'], name='inpatient_i_admissi_33afaf_idx'),
        ),
        migrations.AddField(
            model_name='icuthreshold',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icuthreshold',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseassignment',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='nurseassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseassignment',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_nurse_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnoteamendment',
            name='amended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnoteamendment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnoteamendment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_amendments', to='inpatient.nursingnote'),
        ),
        migrations.AddField(
            model_name='nursingnoteamendment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fluidbalance',
            index=models.Index(fields=['admission', '-balance_date'], name='inpatient_f_admissi_d276d9_idx'),
        ),
        migrations.AddIndex(
            model_name='icumonitoringsheet',
            index=models.Index(fields=['admission', '-monitoring_date'], name='inpatient_i_admissi_5a7740_idx'),
        ),
        migrations.AddConstraint(
            model_name='nurseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('admission', 'nurse'), name='uniq_active_nurse_assignment'),
        ),
    ]
